### ISSUE TITLE
Plugin does not activate

### ISSUE THREAD

**Issue by tm1986** [mitchelldmiller/quick-mail-wp-plugin#12]
Hello,
after uploading the plugin to wordpress and activating i am reveiving the following issue:
 Fatal error: Cannot declare class QuickMailUtil, because the name is already in use in /var/www/XXXXXX/html/XXXX/XXXX/wp-content/plugins/quick-mail-wp-plugin-4.0.0/inc/class-quickmailutil.php on line 13

**Comment by mitchelldmiller** [comment]
Hello @tm1986  :
Please check that you don't have another version of Quick Mail activared.

I had no errors installing Quick Mail on blank WP 5.5.1.

Checked code and `class-quickmailutil.php` is always loaded with `require_once`.

I reproduced your error by:
1. deactivating Quick Mail 4
1. activating Quick Mail 3.5.8
1. reactivating Quick Mail 4 produced your error message.

I am closing issue. Feel free to reopen it, if you can reproduce error.

Best wishes,
Mitchell
