### ISSUE TITLE
Attachments are prefixed by numbers

### ISSUE THREAD

**Issue by mikeyea22** [mitchelldmiller/quick-mail-wp-plugin#15]
The first attachment gets prefix 0, the second #1 etc.
![2021-06-10](https://user-images.githubusercontent.com/36201227/121566822-2eec4d80-ca1e-11eb-92fd-7a04f2159023.png)

**Comment by mitchelldmiller** [comment]
Hello @mikeyea22,
This is correct. I add number [here](https://github.com/mitchelldmiller/quick-mail-wp-plugin/blob/1790a457c13f647ff6e7552a88f4bece1d23e20a/quick-mail.php#L1571).

Prevents duplicate file names.
![numbered_attachments](https://user-images.githubusercontent.com/6073590/121823746-44a78000-cc75-11eb-826e-fad881510431.png)

Best wishes,
Mitchell
