### ISSUE TITLE
Installed update 3.2.6

### ISSUE THREAD

**Issue by castlewrks** [mitchelldmiller/quick-mail-wp-plugin#9]
Get this message:
Parse error: syntax error, unexpected '998' (T_LNUMBER) in /home4/castlewr/public_html/gadgetometers.com/store_v2/wp-content/plugins/quick-mail/quick-mail.php on line 702

Commented out the line in that module with 998 on it to eliminate the error.  Deactivating this plugin till this is fixed.

Robert J Becraft
gadgetometers.com
castlewrks@aol.com

**Comment by mitchelldmiller** [comment]
Good Morning Robert:
I could not reproduce error on PHP 7.0.22 or 5.5.11.
However, line 702 did not make sense.

Replaced
`$msg = empty( 998 < $days ) ? __( 'No comments for you.', 'quick-mail') : __( 'No recent comments for you.', 'quick-mail');`

with
`$msg = ( 998 < $days ) ? __( 'No comments for you.', 'quick-mail') : __( 'No recent comments for you.', 'quick-mail');`

Thank you for report.

Best wishes,
Mitchell
